# Set blank issues as default off to guide users to templates
blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/TharinduNava/Echo-Run/security/advisories/new
    about: Please report security vulnerabilities privately.